// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebChat.Dati;

#nullable disable

namespace WebChat.Migrations
{
    [DbContext(typeof(BancaDati))]
    [Migration("20250528095714_Prima")]
    partial class Prima
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("WebChat.Dati.Strutture.Messaggio", b =>
                {
                    b.Property<uint>("IdMessaggio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Corpo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("DestinatarioIdUtente")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("MittenteIdUtente")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Quando")
                        .HasColumnType("TEXT");

                    b.HasKey("IdMessaggio");

                    b.HasIndex("DestinatarioIdUtente");

                    b.HasIndex("MittenteIdUtente");

                    b.ToTable("messaggi");
                });

            modelBuilder.Entity("WebChat.Dati.Strutture.Utente", b =>
                {
                    b.Property<uint>("IdUtente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdUtente");

                    b.ToTable("utenti");
                });

            modelBuilder.Entity("WebChat.Dati.Strutture.Messaggio", b =>
                {
                    b.HasOne("WebChat.Dati.Strutture.Utente", "Destinatario")
                        .WithMany()
                        .HasForeignKey("DestinatarioIdUtente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebChat.Dati.Strutture.Utente", "Mittente")
                        .WithMany()
                        .HasForeignKey("MittenteIdUtente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destinatario");

                    b.Navigation("Mittente");
                });
#pragma warning restore 612, 618
        }
    }
}
