// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stradario;

#nullable disable

namespace Stradario.Migrations
{
    [DbContext(typeof(BancaDati))]
    [Migration("20250519105915_Seconda")]
    partial class Seconda
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Stradario.Strutture.Arco", b =>
                {
                    b.Property<int>("IdArco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("A")
                        .HasColumnType("INTEGER");

                    b.Property<int>("B")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Creazione")
                        .HasColumnType("TEXT");

                    b.Property<int>("Distanza")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UltimaModifica")
                        .HasColumnType("TEXT");

                    b.HasKey("IdArco");

                    b.ToTable("archi");
                });

            modelBuilder.Entity("Stradario.Strutture.Nodo", b =>
                {
                    b.Property<int>("idNodo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Creazione")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimaModifica")
                        .HasColumnType("TEXT");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("idNodo");

                    b.ToTable("nodi");
                });
#pragma warning restore 612, 618
        }
    }
}
