// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stradario;

#nullable disable

namespace Stradario.Migrations
{
    [DbContext(typeof(BancaDati))]
    [Migration("20250526122503_AddStrade")]
    partial class AddStrade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Stradario.Strutture.Arco", b =>
                {
                    b.Property<int>("IdArco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("A")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("B")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Creazione")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Distanza")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UltimaModifica")
                        .HasColumnType("TEXT");

                    b.HasKey("IdArco");

                    b.ToTable("archi");
                });

            modelBuilder.Entity("Stradario.Strutture.Nodo", b =>
                {
                    b.Property<uint>("idNodo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Creazione")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimaModifica")
                        .HasColumnType("TEXT");

                    b.Property<float>("X")
                        .HasColumnType("REAL");

                    b.Property<float>("Y")
                        .HasColumnType("REAL");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("idNodo");

                    b.ToTable("nodi");
                });

            modelBuilder.Entity("Stradario.Strutture.Strada", b =>
                {
                    b.Property<uint>("IdStrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AidNodo")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("BidNodo")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdStrada");

                    b.HasIndex("AidNodo");

                    b.HasIndex("BidNodo");

                    b.ToTable("strade");
                });

            modelBuilder.Entity("Stradario.Strutture.Strada", b =>
                {
                    b.HasOne("Stradario.Strutture.Nodo", "A")
                        .WithMany()
                        .HasForeignKey("AidNodo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stradario.Strutture.Nodo", "B")
                        .WithMany()
                        .HasForeignKey("BidNodo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("A");

                    b.Navigation("B");
                });
#pragma warning restore 612, 618
        }
    }
}
